name: Run local instance of lookyloo to test that current repo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  splash-container:
     runs-on: ubuntu-latest

     strategy:
       matrix:
         python-version: ["3.8", "3.9", "3.10"]

     steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}

      - name: Install and setup redis
        run: |
          pushd ..
          git clone https://github.com/antirez/redis.git
          pushd redis
          git checkout 6.2
          make
          popd
          popd

      - name: Install system deps
        run: |
          sudo apt install libfuzzy-dev
          # playwright required deps.
          sudo apt install libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxkbcommon0 libxdamage1 libgbm1 libpango-1.0-0 libcairo2 libatspi2.0-0
          python -m pip install --upgrade pip poetry

      - name: Install & run lookyloo
        run: |
          echo LOOKYLOO_HOME="'`pwd`'" > .env
          cp config/generic.json.sample config/generic.json
          cp config/modules.json.sample config/modules.json
          poetry install -vvv
          poetry run playwright install
          poetry run tools/validate_config_files.py --check
          poetry run tools/validate_config_files.py --update
          poetry run tools/3rdparty.py
          poetry run start

      - name: Install pylookyloo and run test
        run: |
          git clone https://github.com/Lookyloo/PyLookyloo.git
          pushd PyLookyloo
          poetry install
          poetry run python tests/testing_github.py
          popd

      - name: Stop instance
        run: |
          poetry run stop
